### ISSUE TITLE
Archive Support

### ISSUE THREAD

**Issue by hevey** [hevey/Documents#2]
Adding a feature to be able to compress and decompress archive files.

Will need to be able to support zip, 7z and rar atleast

**Comment by shaun-h** [comment]
I'll take a look at this one

**Comment by hevey** [comment]
I am thinking that it is just built into the UIDocumentBrowserViewController as an option off the menu when items are picked. Basically if a file is not an archive already it will have and Archive option other wise might have an unarchive option.

**Comment by shaun-h** [comment]
Yeah sounds good, can your assign it to me?

**Comment by shaun-h** [comment]
Extract of zip files has been added, what other file types would you like added

**Comment by hevey** [comment]
7z, rar and tar.gz files. Are you looking at compression into these file types aswell?

**Comment by shaun-h** [comment]
yeah after I have extraction working for all of those

**Comment by shaun-h** [comment]
this is in #23
