### ISSUE TITLE
Add open source screen in app

### ISSUE THREAD

**Issue by shaun-h** [hevey/Documents#20]
We need to add a screen in app for open source libraries we have used to comply with licenses.

**Comment by hevey** [comment]
This can be added under the settings menu

**Comment by shaun-h** [comment]
this is in #23

**Comment by hevey** [comment]
Ok I’m guessing it is ready to merge?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shaun-h** [comment]
yeah take a look
