### ISSUE TITLE
Allow for Creation of Files.

### ISSUE THREAD

**Issue by hevey** [hevey/Documents#5]
Allow for creation of blank file types. 

This could include the following type

- [x] Office Documents Office/Pages files
- [x] Text Files
- [x] Archive File

**Comment by hevey** [comment]
So I am thinking that when the new item button is pushed it will show a UIAlertController with a list of the options of items that can be created. Two things that need to be sorted however is

1.

The best way to handle what items are available to make. Do we look at what applications can handle each filetype and if there are none available then don't show the file type as an option (Unsure if this is even possible).

**Comment by hevey** [comment]
So I am thinking that when the new item button is pushed it will show a UIAlertController with a list of the options of items that can be created. Two things that need to be sorted however is

1. The best way to handle what items are available to make. Do we look at what applications can handle each filetype and if there are none available then don't show the file type as an option (Unsure if this is even possible).
2. If we give the option to add new file types and if so how the workflow for this looks

**Comment by hevey** [comment]
Have implemented this, at the moment I have picked several default filetypes to make. This is using the standard delegate document creation from Apple. 

PR #11 is where this code is at the moment

**Comment by hevey** [comment]
PR #11 updated to use built in document creation provided by Apple

**Comment by hevey** [comment]
Added more creation features in PR #14

**Comment by hevey** [comment]
creating Archives I think needs to be handled when selecting multiple files screen and not from a new file dropdown. What do you think @shaun-h

**Comment by shaun-h** [comment]
Archive support will be submitted soon

**Comment by hevey** [comment]
The main file types have been completed. Closing Issue
