### ISSUE TITLE
Can't overwrite folder when extracting using the current folder option

### ISSUE THREAD

**Issue by hevey** [hevey/Documents#8]
If folder exists already when using the Current Folder option the system throws a System.IO.IOException
<img width="1008" alt="screen shot 2018-04-07 at 2 07 33 pm" src="https://user-images.githubusercontent.com/7008490/38451121-48a9748a-3a6d-11e8-98db-4fd9ef49384d.png">

**Comment by shaun-h** [comment]
fixed and now on develop
